// This file was generated by Prisma and updated for Vercel deployment
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env.DATABASE_URL || "",       
    directUrl: process.env.DIRECT_URL || "", 
  },
});